spring:
  application:
    name: dwh_bi_api
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        generate_statistics: false
        jdbc:
          lob:
            non_contextual_creation: true
  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: UTC

server:
  port: 8081
  undertow:
    always-set-keep-alive: true

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
  api-docs:
    path: /v3/api-docs

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n"
  level:
    root: INFO
    cpb.dwh_bi_api: INFO

jwt:
  secret: ${JWT_SECRET:cpbank@dwh@bi}
  expiration: 86400000

security:
  ignored: /swagger-ui/**,/v3/api-docs/**
