spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://192.168.101.5:5432/dwh_cpb_bi}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:123cp!@#}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate

logging:
  level:
    root: WARN
    cpb.dwh_bi_api: INFO
