security.ignored=/**
jwt.secret=cpbank@dwh@bi

#connection to postgresql
#LOCAL
#spring.datasource.url =jdbc:postgresql://localhost:5432/dwh_cpb_bi
#spring.datasource.username =postgres
#spring.datasource.password =samno106

#UAT
spring.datasource.url =jdbc:postgresql://192.168.103.106:5432/dwh_cpb_bi
spring.datasource.username =postgres
spring.datasource.password =123cp!@#

#PROD
#spring.datasource.url =jdbc:postgresql://192.168.101.5:5432/dwh_cpb_bi
#spring.datasource.username =postgres
#spring.datasource.password =123cp!@#

spring.datasource.driverClassName=org.postgresql.Driver
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
#spring.posql.datasource.driver-class-name=org.postgresql.Driver

server.port=8081
# Enabling H2 Console
spring.h2.console.enabled=true

# Custom H2 Console URL
spring.h2.console.path=/h2-console

# create database schema from SQL files
spring.jpa.hibernate.ddl-auto=update
#hibernate.hbm2ddl.auto=create

#Turn Statistics on and log SQL stmts
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.generate_statistics=false

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
server.undertow.always-set-keep-alive=true

